version: '3.1'

services:
  db:
    container_name: database
    image: 'postgres:15'
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=cinemaadmin
      - POSTGRES_DB=cinemadb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./docker_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: cinemaapp
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db